compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.1.1.cjs

packageExtensions:
  "@wagmi/core@*":
    dependencies:
      "@tanstack/query-core": ">=5.0.0"
  "@walletconnect/modal-ui@*":
    dependencies:
      "lit-html": "*"
  "vite-plugin-checker@*":
    dependencies:
      "optionator": "^0.9.1"
